const express = require("express");
const auth = require("../../middleware/auth");
const createPerson = require("./controllers/createPerson");
const getPerson = require("./controllers/getPerson");
const getPersonById = require("./controllers/getPersonById");
const delPerson = require("./controllers/delPerson");
const editPerson = require("./controllers/editPerson");
const upload = require("../../middleware/upload");
const getStaff = require("./controllers/getStaff");
const getBoard = require("./controllers/getBoard");
const getFounder = require("./controllers/getFounder");
const getPast = require("./controllers/getPast");
const personRouter = express.Router();
personRouter.get("/", getPerson);
personRouter.get("/staff", getStaff);
personRouter.get("/board", getBoard);
personRouter.get("/founder", getFounder);
personRouter.get("/past", getPast);
personRouter.get("/getById/:personId", getPersonById);
personRouter.use(auth);
personRouter.post("/create", upload, createPerson);
personRouter.delete("/del/:personId", delPerson);
personRouter.patch("/edit/:personId", upload, editPerson);
module.exports = personRouter;
