const express = require("express");
const auth = require("../../middleware/auth");
const createSubSection = require("./controllers/createSubSection");
const getSubSection = require("./controllers/getSubSection");
const getSubSectionById = require("./controllers/getSubSectionById");
const delSubSection = require("./controllers/delSubSection");
const editSubSection = require("./controllers/editSubSection");
const upload = require("../../middleware/upload");
const subSectionRouter = express.Router();
subSectionRouter.get("/", getSubSection);
subSectionRouter.get("/:subSectionId", getSubSectionById);
subSectionRouter.use(auth);
subSectionRouter.post("/create", upload, createSubSection);
subSectionRouter.delete("/del/:subSectionId", delSubSection);
subSectionRouter.patch("/edit/:subSectionId", upload, editSubSection);
module.exports = subSectionRouter;
