const express = require("express");
const auth = require("../../middleware/auth");
const entry = require("./controllers/entry");
const multer = require("multer");
const getSheets = require("./controllers/getSheets");
const delSheets = require("./controllers/delSheets");
const upload = multer();
const programRouter = express.Router();
programRouter.post("/entry", upload.single("photo"), entry);
programRouter.get("/", getSheets);
programRouter.delete("/", delSheets);
module.exports = programRouter;
