const express = require("express");
const auth = require("../../middleware/auth");
const createEyeCareCenter = require("./controllers/createEyeCareCenter");
const getEyeCareCenter = require("./controllers/getEyeCareCenter");
const getEyeCareCenterById = require("./controllers/getEyeCareCentersById");
const delEyeCareCenter = require("./controllers/delEyeCareCenter");
const editEyeCareCenter = require("./controllers/editEyeCareCenter");
const eyeCareCenterRouter = express.Router();
eyeCareCenterRouter.get("/", getEyeCareCenter);
eyeCareCenterRouter.get("/:eyeCareCenterId", getEyeCareCenterById);
eyeCareCenterRouter.post("/create", createEyeCareCenter);
eyeCareCenterRouter.delete("/del/:eyeCareCenterId", delEyeCareCenter);
eyeCareCenterRouter.patch("/edit/:eyeCareCenterId", editEyeCareCenter);
module.exports = eyeCareCenterRouter;
