const express = require("express");
const auth = require("../../middleware/auth");
const getHistory = require("./controller/getHistory");
const getLanding = require("./controller/getLanding");
const getMission = require("./controller/getMission");
const getPartnerPage = require("./controller/getPartner");
const getTeamPage = require("./controller/getTeam");
const getWhatWeDo = require("./controller/getWhatWeDo");
const getResourcesPage = require("./controller/getResourcesPage");
const getPressPage = require("./controller/getPressPage");
const getEthicalReviewPage = require("./controller/getEthicalReviewPage");
const getContactPage = require("./controller/getContactPage");
const pageRouter = express.Router();
pageRouter.get("/history", getHistory);
pageRouter.get("/landing", getLanding);
pageRouter.get("/mission", getMission);
pageRouter.get("/partners", getPartnerPage);
pageRouter.get("/whatWeDo", getWhatWeDo);
pageRouter.get("/resources", getResourcesPage);
pageRouter.get("/press", getPressPage);
pageRouter.get("/ethicalReview", getEthicalReviewPage);
pageRouter.get("/contact", getContactPage);
pageRouter.get("/team", getTeamPage);
module.exports = pageRouter;
